"""Remotion compose adapter.

Generates `remotion/src/generated/manifest.ts` from storyboard.yaml + run artifacts,
symlinks artifacts into `remotion/public/`, then invokes `npm run render`.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML

from creativeforge.adapters.base import register

yaml = YAML(typ="safe")


def _load_storyboard(project_dir: Path) -> dict[str, Any]:
    with (project_dir / "storyboard.yaml").open(encoding="utf-8") as f:
        return yaml.load(f)


def _ts_literal(value) -> str:
    """Minimal JSON→TS literal conversion (sufficient for our manifest)."""
    return json.dumps(value, ensure_ascii=False, indent=2)


def generate_manifest(project_dir: Path, run_dir: Path, available_clip_ids: set[str]) -> Path:
    sb = _load_storyboard(project_dir)
    cuts = sb.get("cuts", [])
    subtitles: list[dict] = []
    for c in cuts:
        d = c.get("dialogue")
        if d and d.get("text"):
            subtitles.append(
                {
                    "start": c["start_s"],
                    "end": c["start_s"] + c["duration_s"],
                    "text": d["text"],
                }
            )

    title_card = sb.get("title_card", {"start_s": 28, "duration_s": 2})
    total_seconds = max(
        (title_card["start_s"] + title_card["duration_s"]),
        max((c["start_s"] + c["duration_s"] for c in cuts), default=0),
    )

    ts_content = f"""// AUTO-GENERATED by creativeforge. Edit storyboard.yaml + re-render instead.
export const FPS = {sb.get('fps', 30)};
export const WIDTH = {sb.get('width', 1080)};
export const HEIGHT = {sb.get('height', 1920)};
export const TOTAL_SECONDS = {total_seconds};
export const TOTAL_FRAMES = TOTAL_SECONDS * FPS;

export const TITLE_CARD_SECONDS = {title_card['duration_s']};
export const TITLE_CARD_FRAMES = TITLE_CARD_SECONDS * FPS;

export const AVAILABLE_CLIPS: ReadonlySet<string> = new Set<string>(
  {_ts_literal(sorted(available_clip_ids))}
);

export const CUTS = {_ts_literal([
    {"id": c["id"], "start": c["start_s"], "duration": c["duration_s"], "label": c.get("label", "")}
    for c in cuts
])} as const;

export const SUBTITLES: {{ start: number; end: number; text: string }}[] = {_ts_literal(subtitles)};
"""
    out_dir = project_dir / "remotion" / "src" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = out_dir / "manifest.ts"
    manifest_path.write_text(ts_content, encoding="utf-8")
    return manifest_path


def _link_artifacts(project_dir: Path, run_dir: Path) -> set[str]:
    """Symlink run artifacts into remotion/public/{clips,music,sfx,voice}/.

    Returns the set of clip ids that have an mp4.
    """
    pub = project_dir / "remotion" / "public"
    available_clips: set[str] = set()

    stage_to_subdir = {
        "stage-02-cut-videos": "clips",
        "stage-03-voice": "voice",
        "stage-04-audio": "music",
    }
    for stage, subdir in stage_to_subdir.items():
        src = run_dir / stage
        if not src.is_dir():
            continue
        dest = pub / subdir
        dest.mkdir(parents=True, exist_ok=True)
        for f in src.iterdir():
            if f.suffix.lower() in {".mp4", ".mp3", ".wav"}:
                target = dest / f.name
                if target.exists() or target.is_symlink():
                    target.unlink()
                target.symlink_to(f.resolve())
                if f.suffix.lower() == ".mp4":
                    available_clips.add(f.stem)
    return available_clips


@register("remotion")
class RemotionComposeAdapter:
    name: str

    async def render(self, project_dir: Path, run_dir: Path, out: Path) -> Path:
        available = _link_artifacts(project_dir, run_dir)
        generate_manifest(project_dir, run_dir, available)

        remotion_dir = project_dir / "remotion"
        if not (remotion_dir / "node_modules").exists():
            await self._run(["npm", "install"], cwd=remotion_dir)

        out.parent.mkdir(parents=True, exist_ok=True)
        await self._run(
            ["npx", "remotion", "render", "src/index.ts", "KingsChoice", str(out)],
            cwd=remotion_dir,
        )
        return out

    async def _run(self, cmd: list[str], cwd: Path) -> None:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            cwd=cwd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
        out_b, _ = await proc.communicate()
        if proc.returncode != 0:
            raise RuntimeError(
                f"command {cmd!r} failed (rc={proc.returncode}):\n{out_b.decode(errors='replace')}"
            )
